# Generated by Django 5.2.4 on 2025-07-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_info',
            field=models.TextField(blank=True, help_text='联系方式（微信、QQ、邮箱等）', null=True),
        ),
    ]
