# Generated by Django 5.2.4 on 2025-07-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_mbti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': '用户档案', 'verbose_name_plural': '用户档案'},
        ),
    ]
