# Generated by Django 5.2.4 on 2025-07-24 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_remove_userprofile_birthday_remove_userprofile_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='事件名称', max_length=200)),
                ('start_time', models.DateTimeField(help_text='开始时间')),
                ('end_time', models.DateTimeField(help_text='结束时间')),
                ('is_online', models.BooleanField(default=False, help_text='是否为线上事件')),
                ('logo_url', models.URLField(blank=True, help_text='事件Logo URL', null=True)),
                ('banner_url', models.URLField(blank=True, help_text='事件横幅URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(help_text='事件创建者', on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='事件地点', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='authentication.address')),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '事件',
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '事件参与者',
                'verbose_name_plural': '事件参与者',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='events_even_start_t_c2d277_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location'], name='events_even_locatio_b471aa_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['creator'], name='events_even_creator_f6258f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['user'], name='events_even_user_id_f0927d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event'], name='events_even_event_i_7ee2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['joined_at'], name='events_even_joined__92f422_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('user', 'event')},
        ),
    ]
