# Generated by Django 5.2.4 on 2025-07-24 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_userprofile_birthday_remove_userprofile_email_and_more'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AddField(
            model_name='event',
            name='introduction',
            field=models.TextField(blank=True, help_text='活动描述', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_url',
            field=models.URLField(blank=True, help_text='活动横幅URL', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(help_text='活动创建者', on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_online',
            field=models.BooleanField(default=False, help_text='是否为线上活动'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, help_text='活动地点', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='authentication.address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo_url',
            field=models.URLField(blank=True, help_text='活动Logo URL', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='活动名称', max_length=200),
        ),
        migrations.DeleteModel(
            name='EventParticipant',
        ),
    ]
