# Generated by Django 5.2.4 on 2025-07-27 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_public',
        ),
    ]
