# Generated by Django 5.2.4 on 2025-07-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_buddyrequest_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyrequest',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery任务ID', max_length=255, null=True),
        ),
    ]
