# Generated by Django 5.2.4 on 2025-07-25 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_buddyrequest_celery_task_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='buddyrequest',
            name='matchmaking_start_t_c44143_idx',
        ),
        migrations.RemoveIndex(
            model_name='buddyrequest',
            name='matchmaking_activit_58f518_idx',
        ),
        migrations.RemoveField(
            model_name='buddyrequest',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='buddyrequest',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='buddyrequest',
            name='start_time',
        ),
    ]
