# Generated by Django 5.2.4 on 2025-07-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_remove_buddyrequest_matchmaking_start_t_c44143_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddyrequest',
            name='max_participants',
        ),
    ]
