# Generated by Django 5.2.4 on 2025-07-25 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_description'),
        ('matchmaking', '0005_remove_buddyrequest_max_participants'),
        ('profiles', '0003_alter_userprofile_mbti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='buddyrequest',
            name='matchmaking_status_5b1b5b_idx',
        ),
        migrations.RemoveField(
            model_name='buddyrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='buddyrequest',
            name='is_public',
            field=models.BooleanField(default=False, help_text='是否允许别人找搭子'),
        ),
        migrations.AddIndex(
            model_name='buddyrequest',
            index=models.Index(fields=['is_public'], name='matchmaking_is_publ_219daf_idx'),
        ),
    ]
