# Generated by Django 5.2.4 on 2025-07-24 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='中国', help_text='国家', max_length=50)),
                ('province', models.CharField(help_text='省份/直辖市', max_length=50)),
                ('city', models.CharField(help_text='城市', max_length=50)),
                ('district', models.CharField(blank=True, help_text='区/县', max_length=50, null=True)),
                ('detailed_address', models.CharField(blank=True, help_text='详细地址', max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='纬度', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='经度', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '地址',
                'indexes': [models.Index(fields=['city'], name='authenticat_city_9cef29_idx'), models.Index(fields=['province', 'city'], name='authenticat_provinc_42f182_idx'), models.Index(fields=['city', 'district'], name='authenticat_city_ed91bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, help_text='用户地址', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='authentication.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
    ]
