# Generated by Django 5.2.4 on 2025-07-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_userprofile_birthday_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
